# Automatically generated by Pynguin.
import temp-gen as module_0


def test_case_0():
    int_0 = 1922
    list_0 = [int_0, int_0, int_0]
    var_0 = module_0.func_0(list_0)
    assert var_0 == 11532


def test_case_1():
    int_0 = 1927
    list_0 = [int_0, int_0, int_0]
    var_0 = module_0.func_0(list_0)
    assert var_0 == 0
