# Automatically generated by Pynguin.
import func_0 as module_0

def test_case_0():
    int_0 = 516
    list_0 = [int_0, int_0, int_0]
    var_0 = module_0.func_0(list_0)
    assert var_0 == 1548


def test_case_1():
    int_0 = 3864
    list_0 = [int_0, int_0]
    var_0 = func_0(list_0)
    assert var_0 == 7728
    var_1 = module_0.func_0(list_0)
    assert var_1 == 7728
    var_2 = module_0.func_0(list_0)
    assert var_2 == 7728
    var_3 = module_0.func_0(list_0)
    assert var_3 == 7728
    list_1 = []
    var_4 = module_0.func_0(list_1)
    assert var_4 == 0
    int_1 = 2
    list_2 = []
    var_5 = module_0.func_0(list_2)
    assert var_5 == 0
    var_6 = module_0.func_0(list_2)
    assert var_6 == 0
    var_7 = module_0.func_0(list_2)
    assert var_7 == 0
    var_8 = module_0.func_0(list_2)
    assert var_8 == 0
    int_2 = 469
    var_9 = module_0.func_0(list_1)
    assert var_9 == 0
    list_3 = []
    var_10 = module_0.func_0(list_3)
    assert var_10 == 0
    list_4 = [int_0, int_2]
    var_11 = module_0.func_0(list_4)
    assert var_11 == 4333
    list_5 = [int_1, int_1, int_1, int_2]
    var_12 = module_0.func_0(list_5)
    assert var_12 == 469
    var_13 = module_0.func_0(list_5)
    assert var_13 == 469
    var_14 = module_0.func_0(list_5)
    assert var_14 == 469
    list_6 = [int_1, int_1]
    var_15 = module_0.func_0(list_3)
    assert var_15 == 0
    var_16 = module_0.func_0(list_6)
    assert var_16 == 0
    var_17 = module_0.func_0(list_6)
    assert var_17 == 0
